version: "3.3"
services:
  home:
    build: home/
    # env_file: ./database.env #environment variable file
    volumes:
      - ./home:/app
    depends_on:
      - redis
    ports:
      - "5000:5000"
    restart: always
    command: gunicorn -w 1 -b :5000 app:app
  accounts:
    build: accounts/
    # env_file: ./database.env #environment variable file
    volumes: 
      - ./accounts:/app
    depends_on:
      - redis
    ports:
      - "5001:5001"
    restart: always
    command: gunicorn -w 1 -b :5001 app:app
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - home
  redis:
    image: redis
  # database:
  #   image: postgres #if using an existing image
  #   restart: always #what to do if container crashes
  #   env_file: ./database.env
  #   environment:
  #     - POSTGRES_USER=root # specify individual env variables.
 
