version: "3.3"
services:
  backend:
    build: backend/
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    ports:
      - "8000:8000"
    restart: always
    command: gunicorn -w 1 -b :8000 app:app
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
  redis:
    image: redis

 
